# Generated by Django 5.2.5 on 2025-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scrapesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedregister',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedregister',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedregister',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
