# Generated by Django 5.2.5 on 2025-09-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_generatedregister_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='previous_legal_registers',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
