# Generated by Django 5.2.5 on 2025-09-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_document_previous_legal_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousLegalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=512)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('json_path', models.CharField(blank=True, default='', max_length=1024)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='uploaded', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previous legal register',
                'verbose_name_plural': 'Previous legal registers',
                'ordering': ['-created_at'],
            },
        ),
    ]
